name: Latest Substack Posts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-substack:
    name: Update this repo's README with latest Substack posts
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://yoursubstack.substack.com/feed
          readme-section: '## Latest Substack Posts'
          max: 5
